# Generated by Django 4.0.1 on 2022-01-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachable',
            old_name='subject',
            new_name='subjects',
        ),
    ]
