# Generated by Django 4.0.1 on 2022-02-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_tutor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='daypart',
            field=models.CharField(choices=[(1, 'all'), (2, 'morning'), (3, 'evening')], max_length=20),
        ),
    ]
