# Generated by Django 4.0.1 on 2022-02-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_alter_tutor_daypart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='daypart',
            field=models.CharField(choices=[('1', 'all'), ('2', 'morning'), ('3', 'evening')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='teachables',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='tutor.Teachable'),
        ),
    ]
