# Generated by Django 4.0.1 on 2022-01-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('subjects', models.ManyToManyField(to='section.Subject')),
            ],
        ),
    ]
