# Generated by Django 4.0.1 on 2022-01-31 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_chapter_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='number',
            new_name='chapter_number',
        ),
    ]
