# Generated by Django 4.0.1 on 2022-02-07 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_tutor_is_active'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='democlasses', to='student.student')),
                ('teachables', models.ManyToManyField(to='tutor.Teachable')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='democlasses', to='tutor.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='student.student')),
                ('teachables', models.ManyToManyField(to='tutor.Teachable')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='tutor.tutor')),
            ],
        ),
    ]
