# Generated by Django 4.0.1 on 2022-02-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_democlass_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='daypart',
            field=models.CharField(choices=[('1', 'all'), ('2', 'morning'), ('3', 'evening')], max_length=20),
        ),
    ]
