# Generated by Django 4.0.1 on 2022-02-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_classroomreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomreport',
            name='last_modified',
        ),
    ]
