# Generated by Django 4.0.1 on 2022-02-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_classroomreport_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomreport',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
