# Generated by Django 4.0.1 on 2022-02-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_classroomreport_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
